# Generated by Django 6.0.7 on 2026-08-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
